#!/usr/bin/env python3
"""Render the deterministic portfolio index from portfolio/catalog.json."""

from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict
from pathlib import Path


def render(catalog: dict) -> str:
    groups: OrderedDict[str, list[dict]] = OrderedDict()
    for item in catalog["repositories"]:
        groups.setdefault(item["group"], []).append(item)

    lines: list[str] = [
        "# Jors Academy Portfolio Index",
        "",
        "> Generated from `portfolio/catalog.json`. Do not edit this file by hand.",
        "",
        "This index is the deterministic machine-generated companion to the curated `PORTFOLIO_MAP.md`.",
        "",
    ]

    for group, items in groups.items():
        lines.extend([f"## {group}", "", "| Repository | Axis | Area |", "|---|---|---|"])
        for item in sorted(items, key=lambda x: x["title"].lower()):
            url = f"https://github.com/{catalog['owner']}/{item['repository']}"
            lines.append(f"| [{item['title']}]({url}) | `{item['axis']}` | `{item['area']}` |")
        lines.append("")

    lines.extend(["## Source of truth", "", "- Human navigation: [`PORTFOLIO_MAP.md`](PORTFOLIO_MAP.md)", "- Governance contract: [`docs/portfolio-governance.md`](docs/portfolio-governance.md)", "- Machine catalog: [`portfolio/catalog.json`](portfolio/catalog.json)", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, default=Path("portfolio/catalog.json"))
    parser.add_argument("--output", type=Path, default=Path("PORTFOLIO_INDEX.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads(args.catalog.read_text(encoding="utf-8"))
    expected = render(catalog)
    if args.check:
        if not args.output.exists():
            print(f"ERROR: {args.output} does not exist", file=sys.stderr)
            return 1
        current = args.output.read_text(encoding="utf-8")
        if current != expected:
            print(f"ERROR: {args.output} is out of date; run scripts/render_portfolio_index.py", file=sys.stderr)
            return 1
        print(f"{args.output} is up to date.")
        return 0
    args.output.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
